Module_1_hello_microverse_project
assadounto/MicroverseProject1 pull request #1
Opened 2022-04-20 18:34 UTC by assadounto

2022-04-20 18:57 UTC, phelian23 requested changes
Hi @assadounto, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Good commit messages

## Required Changes ♻️

- [ ] Kindly add a summary to your pull request describing the introduced changes in more detail.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 18:57 UTC, phelian23 commented on README.md
- [ ] A professional README should include instruction steps to run the app locally for the sake of the non-technical user. Kindly include steps to clone and run the app locally.

2022-04-20 18:57 UTC, phelian23 commented on .gitignore
> +.stylelintrc.json
- [ ] The `.hintrc` and `.stylelintrc.json` files should not be added to the .gitignore file kindly remove it

2022-04-20 20:06 UTC, assadounto commented
@phelian23 I have done most of the changes requested

2022-04-20 20:37 UTC, assadounto commented
Hello,
Following the requested changes, I have  committed them. Please review


On Wed, Apr 20, 2022, 6:57 PM Oluwafemi Awoyemi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @assadounto <https://github.com/assadounto>,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
> ✅ Good commit messages
> Required Changes ♻️
>
>    - Kindly add a summary to your pull request describing the introduced
>    changes in more detail.
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
>    - x
>    - y
>    - z
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/assadounto/MicroverseProject1/pull/1#discussion_r854452666>
> :
>
> >
>
> -### Prerequisites
>
> -
>
> -### Setup
>
> -
>
> -### Install
>
> -
>
> -### Usage
>
> -
>
> -### Run tests
>
> -
>
> -### Deployment
>
> -
>
> -
>
>
>
>
>
>    - A professional README should include instruction steps to run the
>    app locally for the sake of the non-technical user. Kindly include steps to
>    clone and run the app locally.
>
> ------------------------------
>
> In .gitignore
> <https://github.com/assadounto/MicroverseProject1/pull/1#discussion_r854456107>
> :
>
> > +.hintrc
>
> +.stylelintrc.json
>
>
>
>    - The .hintrc and .stylelintrc.json files should not be added to the
>    .gitignore file kindly remove it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/assadounto/MicroverseProject1/pull/1#pullrequestreview-947617934>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW2UEV4QWLSBDLH4ZLZJGLDVGBHSVANCNFSM5T442VMA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-21 12:57 UTC, ShadyShawkat approved these changes
## Hi @assadounto, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 13:05 UTC, merged